<a href="https://colab.research.google.com/github/nicabey/Numerical-Methods/blob/main/Project4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Project 4 
Numerical Methods 

Dr. Jacob 

Laxman Bista, Nichole Beyer, Ritu Mahrarjan, Sanjay Katuwal


# Gauss-Jordan Method

Gauss-Jordan Elimination method is an algorithm that can be used to solve systems of linear equations. It also helps to find the inverse of any invertible matrix.
<br>
<br>
-Normally, we use echelon method to finish the Gauss-Jordan Method fully.
<br>
<br> 
-We need linear equations to perform Gauss-Jordan Method. The system of linear equation is a set of two linear equations with two variables, suppose x and y. So, the linear equations are of form below:
$$
\left\{
\begin{align}
a_{1,1} x_1 +&\dots a_{1,n} x_n = y_1\\
&\vdots\\
a_{n,1}x_1+&\dots a_{n,n} x_n = y_n
\end{align}
\right\}
$$
<br>
Augmented Matrix: In simple words, a matrix with only the coefficients of a system of linear equation.
Suppose we have a following linear equations:
$$
3x_1 + 2x_2 + 3x_3 = 5 ----- (equation.i) 
\\
1.x_1 + 3x_2 + 5x_3 = 7 ----- (equation.ii) 
\\
1.x_1 + 1.x_2 - 2x_3 = 4 ----- (equation.iii) 

$$
The augmented matrix for the above 3 equations would be:

$$
\left[
\begin{align}
2 1 3
\\
13 5
\\
1 1 2
\end{align}
\right]
$$



In [ ]:
 # importing math and numpy library
import math
import numpy as np

# let's create our first 3*3 matrix using numpy
first_array = np.array([[1,2,3],[2,3,4]])
first_array

array([[1, 2, 3],
       [2, 3, 4]])

# Adding Row to a Matrix

We are using numpy.vstack to add a row of matrix in vertical sequence.
<br>
**Constraints** 
<br>
-The arrays must have the same shape along all but the first axis, 1-D arrays must have the same length.
<br>
**Return:**
<br>
-The array formed by stacking the given arrays, will be at leat 2-D (stacked: ndarray)

In [ ]:
def addingRows(matrix, row, modifyrow,n):
  newRow = matrix[row, :] + n*matrix[modifyrow, :]
  newMatrix = []
  for i in range(len(matrix)): 
    if i != row:
      newMatrix.append(newRow)
    else:
        newMatrix.append(matrix[i,:])
        return np.array(newMatrix)

In [ ]:
addingRows(first_array,1,0,1)

array([[3, 5, 7],
       [2, 3, 4]])

In [ ]:
##For shape of the above array, you can check with the following method:

In [ ]:
first_array.shape


(2, 3)

We can see above that we have 2*3 matrix

# Swap rows in a Matrix

lets consider a matrix:
A = np.array([<br>[1,2,3],<br>
              [4,5,6],<br>
              [7,8,9]<br>])<br>
Let's try to change row 1 indexed at '0' with 3rd row which is at 1st index


In [ ]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
A[[0,2]] = A[[2,0]]
A

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

# Second Method to Swap rows using Function

Let's create a 2*2 matrix

In [ ]:
B = np.array([[1,2],[3,4]])

In [ ]:
def swap(matrix,firstrow,secondrow):
  newMatrix = []
  for i in range(len(matrix)):
    if i == firstrow:
      newMatrix.append(matrix[secondrow,:])
    elif i == secondrow:
      newMatrix.append(matrix[firstrow,:])
    else:
      newMatrix.append(matrix[i,:])
  return np.array(newMatrix)

In [ ]:
swap(B,0,1)

array([[3, 4],
       [1, 2]])

**Conclusion**
Above, can see we used a simple logic to change the position of rows

In [ ]:
##Multiplying by a constant
def MultiplyByConstant(matrix,row,n):
  newRow = n*matrix[row, :]
  newMatrix = []
  for i in range(len(matrix)): 
    if i == 0:
      newMatrix.append(newRow)
    else:
        newMatrix.append(matrix[i,:])
        return np.array(newMatrix)

## to test our code lets multiply the first row by 2 
MultiplyByConstant(B,0,2)

array([[2, 4],
       [3, 4]])

In [ ]:
## the system given in the assignment written as a matrix, N. 
N = np.array([[1,-2,2],[2,-4,4]])
N

N [0][0]
## the code above finds picks out an individual value in the matrix 

1

In [ ]:
## use gauss jordan method to put matrix into Reduced row echelon form. I think I have to make a function that does it for me. so If the first entry in the first collumn is a 1 then great, now i want the row under it to have a zero there so ill do the element of the next row will be added to the folowing row and then multipiled to give the result of a zero 
## lets try 

def toLeadingOne(matrix,row,column):
  newMatrix =[]
  for i in range(len(matrix)):
    if i != row:
      newMatrix.append(matrix[i,:])
    else:
      newMatrix.append(1/matrix[row,column]*matrix[row,:])
  return np.array(newMatrix)


In [ ]:
toLeadingOne(A,1,0)

array([[1.  , 2.  , 3.  ],
       [1.  , 1.25, 1.5 ],
       [7.  , 8.  , 9.  ]])

Now lets use a Gauss Jordan Method

In [ ]:
A = np.array([[1,2,3],[2,3,4]])


In [ ]:
def gaussJordan(matrix):
  newMatrix = matrix
  for pivot in range(len(matrix)):
    newMatrix = toLeadingOne(newMatrix,pivot,pivot)
    for column in range(0,pivot):
      newMatrix = addingRows(newMatrix,column,pivot,-newMatrix[column,pivot])
    for column in range(pivot+1,len(matrix)):
      newMatrix = addingRows(newMatrix,column,pivot,-newMatrix[column,pivot])
  return newMatrix

In [ ]:
gaussJordan(A)

array([[ 0., -1., -2.]])

In [ ]:
B = np.array([[1,2,3,4],[2,3,4,5],[3,4,5,6]])

In [ ]:
gaussJordan(B)

IndexError: ignored

In [ ]:
B = addingRows(B,1,0,-2)
B

array([[ 0, -1, -2, -3],
       [ 2,  3,  4,  5]])

In [ ]:
B = addingRows(B,1,0,-1)
B

array([[2, 4, 6, 8],
       [2, 3, 4, 5]])

In [ ]:
##now preforming the gauss Jordan method on the matrix given in the assignment defined as N

gaussJordan(N)

array([[0., 0., 0.]])

So it doesnt look look like the gauss Jordan method is working. Not sure why but it may have something to do with the entire row of zeros being on the top.
Lets do it ourselves its simple, just add 2* row 1 to row 2 and then the matrix should be in reduced row echelon form.

In [ ]:
addingRows(A,0,1,1)

array([[1, 2, 3]])

The last row is all zeros so the code doesnt include it after preformong the operation. 

# Computing Inverses

We can get inverse by aumenting the identity matrix and perform operations util we get the inverse
$$
\left[A|I\right] \to \left[I|A^{-1}\right]
$$

Let's try it on 
$$
A=\left[
\begin{array}{cc}
5&6\\
7&8
\end{array}
\right]
$$


In [ ]:
C = np.array([[1,2,1,0],[3,4,0,1]])

In [ ]:
gaussJordan(C)

array([[ 0., -2., -3.,  1.]])

In [ ]:
inverse = np.array([[-2,1],[1.5,-.5]])
newArray = np.array([[1,2],[3,4]])

In [ ]:
newArray @ inverse

array([[1., 0.],
       [0., 1.]])

Nice we can see our code is working and we got the inverse for the matrix.


# Using some packages in Python

Let's use a package called scipy for scientific computation in python.
Here, linalg means linear algebra

In [ ]:
import scipy.linalg as la

la.inv(newArray)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

Providing the equation with the coefficient and solutions

In [ ]:
la.solve(A[:,:2],A[:,2])

array([-1.,  2.])

# Fix our Gauss-Jordan

In order to fix this issue we will work with the pivot.


In [ ]:
def findLargestPivot(matrix, column):
  vec = matrix[column:,column]
  vec = np.abs(vec)
  row = np.where(vec == max(vec))
  return row[0][0]+column

In [ ]:
vec = np.array([[1,2,-4],[-2,-5,2]])
np.abs(vec)

array([[1, 2, 4],
       [2, 5, 2]])

In [ ]:
findLargestPivot(vec,1)

1

Let's make our row the leading one and follow the above functions

In [ ]:
def gaussJordan2(matrix):
  newMatrix = matrix
  for pivot in range(len(matrix)):
    newpivot = findLargestPivot(newMatrix,pivot)
    newMatrix = swap(newMatrix,newpivot,pivot)
    newMatrix = toLeadingOne(newMatrix,pivot,pivot)
    for column in range(0,pivot):
      newMatrix = addingRows(newMatrix,column,pivot,-newMatrix[column,pivot])
    for column in range(pivot+1,len(matrix)):
      newMatrix = addingRows(newMatrix,column,pivot,-newMatrix[column,pivot])
  return newMatrix

In [ ]:
gaussJordan2(vec)

array([[ 0. , -0.5, -3. ]])

The main obstacle in this work is working with pivot and columns which are fresh and does not have a leading ones. Gauss jordan's method has useful algorithm's we can make use of.